/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet.UI;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import projet.sih.Patient;

/**
 *
 * @author Tommy
 */
public class DemandeConsHospUI extends javax.swing.JFrame {
    private Patient currentPatient;
    private ServiceAdmissionUI serviceAdmissionUI;
    private AjoutRdvUI ardvUI;
    private AjouterHospitalisationUI ahUI;
    private String serviceTransmis = "";
    
    /**
     * Creates new form DemandeConsHosp
     */
    public DemandeConsHospUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonCons = new javax.swing.JButton();
        jButtonHosp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Voulez vous envoyer le patient en consultation ou en hospitalisation ?");

        jButtonCons.setText("Consultation");
        jButtonCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsActionPerformed(evt);
            }
        });

        jButtonHosp.setText("Hospitalisation");
        jButtonHosp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHospActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCons)
                        .addGap(153, 153, 153)
                        .addComponent(jButtonHosp))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonHosp)
                    .addComponent(jButtonCons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsActionPerformed
        try {
            ardvUI = new AjoutRdvUI();
            ardvUI.setLocationRelativeTo(null);
            ardvUI.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            ardvUI.setCurrentPatient(currentPatient);
            ardvUI.setServiceAdmission(serviceAdmissionUI);
            if(!(serviceTransmis.equals(""))){
                DefaultComboBoxModel dcbm = new DefaultComboBoxModel();
                dcbm.addElement(serviceTransmis);
                ardvUI.getjComboBoxService().setModel(dcbm);
                ardvUI.getjComboBoxService().setSelectedIndex(0);
            }
            ardvUI.setVisible(true);
            setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(ServiceAdmissionUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonConsActionPerformed

    private void jButtonHospActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHospActionPerformed
         try {
            ahUI = new AjouterHospitalisationUI();
            ahUI.setCurrentPatient(currentPatient);
            ahUI.setLocationRelativeTo(null);
            ahUI.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            ahUI.setServiceAdmission(serviceAdmissionUI);
            if(!(serviceTransmis.equals(""))){
                DefaultComboBoxModel dcbm = new DefaultComboBoxModel();
                dcbm.addElement(serviceTransmis);
                ahUI.getjComboBoxService().setModel(dcbm);
                ahUI.getjComboBoxService().setSelectedIndex(0);
            }
            ahUI.setVisible(true);
            setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(ServiceAdmissionUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonHospActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCons;
    private javax.swing.JButton jButtonHosp;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    /**
     * @param currentPatient the currentPatient to set
     */
    public void setCurrentPatient(Patient currentPatient) {
        this.currentPatient = currentPatient;
    }

    /**
     * @param serviceAdmissionUI the serviceAdmissionUI to set
     */
    public void setServiceAdmissionUI(ServiceAdmissionUI serviceAdmissionUI) {
        this.serviceAdmissionUI = serviceAdmissionUI;
    }

    /**
     * @param serviceTransmis the serviceTransmis to set
     */
    public void setServiceTransmis(String serviceTransmis) {
        this.serviceTransmis = serviceTransmis;
    }
}
